-- AlterTable
ALTER TABLE "places" ADD COLUMN     "acceptsCashOnly" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "acceptsCreditCards" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "acceptsDebitCards" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "acceptsNfc" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "delivery" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "dine_in" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "directionsUri" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "freeParkingLot" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "freeStreetParking" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "good_for_children" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "good_for_groups" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "good_for_watching_sports" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "googleMapsUri" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "google_average_rating" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "google_total_reviews" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "internationalPhoneNumber" TEXT,
ADD COLUMN     "live_music" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "menu_for_children" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "nationalPhoneNumber" TEXT,
ADD COLUMN     "outdoor_seating" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "paidParkingLot" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "photosUri" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "placeUri" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "priceLevel" TEXT NOT NULL DEFAULT 'PRICE_LEVEL_UNSPECIFIED',
ADD COLUMN     "reservable" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "restroom" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "reviewsUri" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "serves_beer" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "serves_breakfast" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "serves_brunch" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "serves_cocktails" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "serves_coffee" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "serves_dessert" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "serves_dinner" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "serves_lunch" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "serves_vegetarian_food" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "serves_wine" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "take_out" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "timeZone" TEXT NOT NULL DEFAULT 'Asia/Kolkata',
ADD COLUMN     "valetParking" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "websiteUri" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "wheelchairAccessibleEntrance" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "wheelchairAccessibleParking" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "wheelchairAccessibleRestroom" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "wheelchairAccessibleSeating" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "writeAReviewUri" TEXT NOT NULL DEFAULT '';
